language: go

go:
  - "1.11.x"

script:
  - env GO111MODULE=on go test -cover ./...

notifications:
  slack:
    secure: o+IcPxpb/G3KDViWqiAe5yXbehnjF5FCxE556BLwjWEmI2eSAKGZepSfsLgX16sWwDx0aRnWWCpLrh5Um7UmSAzkraua6H8KOzT6AVELA7jHhX10SzMoVvcJjsZex/PJrdd+zFOkqe9ClJjpD3VPQFeyD5vsAxxXaGkMTQQYFM0h9w3I4pKVTTMwKN48EeIgWYRoy3CW7+XTTLCY4PHum6RjFR8pVbk7UyNSEr6znxbg5fO7i1N1R7Z3/6FAbKK2xE+tI0fEXumwOtPsz4E1nLlOne6pYjsNfoRHD/X6H0vlB4itQgx5knGs/FOwLI6Q/5M5WVHn0sLhvt6FaxxP0m07y7QG89MAzpIAgK41PwdKPZhzcShRbjtfN8FTohUZ82+enaWCP++IjBxIcsnqJ7NqRgRSivPqHdIjny9TjG+ofTigrsgcss3c8gNzATGy5NXV+QVpHKYBW8B7LwNOHVxsPQiunSbFQ8/OOps0mmQQ6NctqZTWuN0bW4cJYsIXlAPbg+eWbQC0BqVMDWnLP3PZwS9FSUU3kjdt0s+f3L9yPN9f11oN+oZYNRI/GguB+4zCVGFHe2XFjp2hr+v4uNZtzbucfvgQeeVACJJEn5wMV8OgKR3baNSr06SswuySTjpCy6x9tKbADbILeC3JBhmtg+0DJSi9RLf/ziaGKBw=
